### ISSUE TITLE
Image loading status

### ISSUE THREAD

**Issue by loranger** [ayamflow/vue-loader-mixin#2] opened 2015-05-26 15:28 UTC
Hello,

I cannot figure out my load:progress event is not triggered when I try to load an image (load:start and load:complete works perfectly)
Is there something obvious I missed ?

**Comment by ayamflow** [comment] 2015-05-26 15:34
Now that you mention it, I'm not sure `resource-loader` (the dependency I use to delegate the loading) triggers `progress` events for images. I'll check & update the docs if needed.

**Comment by ayamflow** [comment] 2015-05-26 18:19
Yep, as you can see [here](https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L260), images are loaded using an `<img>` hence no progress event.

I'm not sure if I should add some configuration options to the mixin or leave the default?

**Comment by loranger** [comment] 2015-05-26 19:41
Hmm that sound legit, even if a loader is better with a [progress status](http://usablica.github.io/progress.js/).
I did search a little too and found that a simple way is to load images using an [ajax request](http://blogs.adobe.com/webplatform/2012/01/13/html5-image-progress-events/) which may cause issues with cross domains...
Maybe you have a better solution ? (I would really like you found a way to achieve it)

**Comment by ayamflow** [comment] 2015-05-26 20:11
I thought `resource-loader` handled to force XHR/Ajax with config, but I just tested and it doesn't trigger `progress` event, I guess it's by design.
Since I'm relying on it I'm kind of stuck, and I don't really want to change the dependency (for now) or load images via XHR because it can create all sorts of issues (caching, cross browser, cross domain).

I would recommend choosing yourself a loading library that supports % progress and adapting `vue-loader-mixin` to it.

By the way, I used to depend on [preloadjs](http://createjs.com/PreloadJS) before but changed to `resource-loader` to avoid potential errors with XHR, and also to use a library that is available on npm (you have to shim preloadjs to make it work). If you're interested in using preloadjs you can use [this commit ](https://github.com/ayamflow/vue-loader-mixin/blob/fe9fc2f61a943fd471c6f78cd2945dc1af67b0be/index.js).

**Comment by loranger** [comment] 2015-05-26 20:14
I understand.
Thank you for the preloadjs commit (and for this vue-mixin, by the way)

**Comment by ayamflow** [comment] 2015-05-26 20:20
:+1: it should do the trick. Closing then.

**Closed as completed by ayamflow** 2015-05-26 20:20 UTC
Labels: question
